apiVersion: apps/v1
kind: Deployment
metadata:
  name: people-api
  labels:
    app: people-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: people-api
  template:
    metadata:
      labels:
        app: people-api
    spec:
      containers:
      - name: people-api
        image: gcr.io/PROJECT_ID/people-api:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: people-api-service
spec:
  selector:
    app: people-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer